AWSTemplateFormatVersion: "2010-09-09"
Description: Continuous integration pipeline
Transform: AWS::Serverless-2016-10-31

Parameters:
  GithubOwner:
    Type: String
    Default: faboulaye
  RepositoryName:
    Type: String
    Default: ecs-tuto
  BranchName:
    Type: String
    Default: develop
  Stage:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  LogRetentionInDays:
    Type: Number
    Description: CloudWatch Logs retention period before deletion
    Default: 5
  ECSTutoRepositoryUri:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /test/ecs-tuto/repository_uri

Resources:
  ContinuousIntegration:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${AWS::StackName}-pipeline
      PipelineType: V2
      RoleArn: !GetAtt ContinuousIntegrationRole.Arn
      ArtifactStore:
        Location: !Ref ContinuousIntegrationArtifactStore
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeStarSourceConnection
              OutputArtifacts:
                - Name: SourceArtifact
              Configuration:
                ConnectionArn: !GetAtt GithubConnection.ConnectionArn
                FullRepositoryId: !Sub ${GithubOwner}/${RepositoryName}
                BranchName: !Ref BranchName
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: !Ref ECSTutoBuildProject
                EnvironmentVariables: !Sub >-
                  [
                    {
                      "name": "REPOSITORY_URI",
                      "value": "${ECSTutoRepositoryUri}",
                      "type":"PLAINTEXT"
                    }
                  ]
              InputArtifacts:
                - Name: SourceArtifact
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CodeDeployToECS
              Configuration:
                ApplicationName: ECSTutoApplication
                AppSpecTemplateArtifact: BuildArtifact
                DeploymentGroupName: ecs-deployment-group
                TaskDefinitionTemplatePath: .aws/ecs-task-definition/taskdef.json
                AppSpecTemplatePath: .aws/specs/appspec.yml
                TaskDefinitionTemplateArtifact: BuildArtifact
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1
      Tags:
        - Key: Name
          Value: Continuous Integration Pipeline
        - Key: Application
          Value: Continuous Integration

  ContinuousIntegrationArtifactStore:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-ci-artifact-store
      Tags:
        - Key: Name
          Value: Continuous Integration Artifact Store
        -  Key: Application
           Value: Continuous Integration



  GithubConnection:
    Type: AWS::CodeStarConnections::Connection
    Properties:
      ConnectionName: ecs-tuto-github-connection
      ProviderType: GitHub
      Tags:
        - Key: Application
          Value: Continuous Integration

  ECSTutoBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${RepositoryName}-ci-build-project
      ServiceRole: !GetAtt ECSTutoBuildProjectRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Source:
        Type: CODEPIPELINE
        BuildSpec: .aws/specs/buildspec.yml
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref ECSTutoBuildProjectLog
          Status: ENABLED
      Tags:
        - Key: Name
          Value: ECS Tutorial codebuild
        - Key: Application
          Value: Continuous Integration

  ContinuousIntegrationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-ci-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: !Sub ${AWS::StackName}-ci-policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
                  - s3:PutObject
                Resource:
                  - !GetAtt ContinuousIntegrationArtifactStore.Arn
                  - !Sub ${ContinuousIntegrationArtifactStore.Arn}/*
              - Effect: Allow
                Action:
                  - codestar-connections:UseConnection
                Resource:
                  - !Ref GithubConnection
              - Effect: Allow
                Action:
                  - codebuild:*
                Resource: "*"

  ECSTutoBuildProjectRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${RepositoryName}-ci-codebuild-role
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                  - logs:*
                  - codebuild:*
                  - events:*
                  - dynamodb:*
                  - ecr:*
                  - codebuild:*
                  - codedeploy:*
                Resource: "*"

  ECSTutoCodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: CodeDeployRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:*
                  - ecr:*
                  - logs:*
                  - s3:*
                Resource: '*'

  ECSTutoBuildProjectLog:
    Type: AWS::Logs::LogGroup
    UpdateReplacePolicy: Delete
    DeletionPolicy: Delete
    Properties:
      LogGroupName: !Sub /aws/codebuild/${RepositoryName}-ci-build-project
      RetentionInDays: !Ref LogRetentionInDays