AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Tutorial - Infrastructure
Transform: AWS::Serverless-2016-10-31

Parameters:
  Project:
    Type: String
    Default: ECS Tutorial Cluster
  RepositoryName:
    Type: String
    Default: ecs-tuto
  App:
    Type: String
    Default: ecs-tuto
  Stage:
    Type: String
    Default: test
    AllowedValues:
      - dev
      - test
      - prod

Resources:
  ECSTutoRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName

  ECSTutoCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub ${Stage}-${AWS::StackName}-cluster
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1
        - CapacityProvider: FARGATE_SPOT
          Weight: 1
      Tags:
        - Key: Project
          Value: !Ref Project
        - Key: Application
          Value: !Ref App
        - Key: Environment
          Value: !Ref Stage

  ECSTutoClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Stage}-${AWS::StackName}-cluster-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  ECSTutoRepositoryParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Type: String
      Name: !Sub /${Stage}/${App}/repository_uri
      Value: !GetAtt ECSTutoRepository.RepositoryUri
      Tags:
        Application: !Ref App
        Stage: !Ref Stage
        Project: !Ref Project